 [build]
# Generate Swagger docs before initial build
pre_cmd = ["swag init -g main.go"]
# Generate Swagger docs AND build before each reload
cmd = "swag init -g main.go && go build -o ./tmp/main ."
args_bin = []
bin = "./tmp/main"
delay = 1000
# Add "docs" to the exclude_dir list
exclude_dir = ["assets", "tmp", "vendor", "testdata", "node_modules", ".git", "docs"]
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = []
include_ext = ["go", "tpl", "tmpl", "html"]
include_file = []
kill_delay = "0s"
log = "build-errors.log"
rerun = true
rerun_delay = 500
send_interrupt = true
stop_on_root = false
