run:
  timeout: 5m
  tests: true
linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/fuzumoe/urlinsight-backend
issues:
  exclude-dirs:
    - "vendor"
  exclude-files:
    - ".*\\.gen\\.go"
  exclude-rules:
    - path: _test\\.go
      linters:
        - errcheck
  max-same-issues: 0
linters:
  # Only enable the most reliable linters
  enable:
    - govet
    - gofmt
    - goimports
    - revive
  disable-all: true
    - scopelint   
dupl:
  threshold: 50
gocyclo:
  min-complexity: 15
