run:
  timeout: 5m
  tests: true
linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/fuzumoe/urlinsight-backend
  unused:
    check-exported: true
  gosimple:
    checks: ["all"]
  staticcheck:
    checks: ["all"]
  revive:
    ignore-generated-header: true
    severity: warning
issues:
  exclude-dirs:
    - "vendor"
  exclude-files:
    - ".*\\.gen\\.go"
  exclude-rules:
    - path: _test\\.go
      linters:
        - errcheck
  max-same-issues: 0
linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - unused
    - ineffassign
    - typecheck
    - unconvert
    - gofmt
    - goimports
    - misspell
    - gocyclo
    - dupl
    - revive
  disable:
    - nakedret    
    - maligned    
    - deadcode    
    - structcheck 
    - varcheck    
    - nakedret    
    - scopelint    
    - goanalysis_metalinter
dupl:
  threshold: 50
gocyclo:
  min-complexity: 15
