run:
  timeout: 5m
  tests: true

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/fuzumoe/linkTorch-api
  revive:
    ignore-generated-header: true
    severity: warning

issues:
  exclude-dirs:
    - "vendor"
    - "tests"
  exclude-files:
    - ".*\\.gen\\.go"
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - linters:
        - goanalysis_metalinter
      text: "Cannot range over: func\\(yield func\\(.*\\) bool\\)"
  max-same-issues: 0

linters:
  enable:
    - govet
    - errcheck
    - ineffassign
    - unconvert
    - gofmt
    - goimports
    - misspell
    - gocyclo
    - dupl
    - revive
  disable:
    # Deprecated linters (remove to avoid warnings)
    - maligned
    - deadcode
    - structcheck
    - varcheck
    - scopelint
    # Temporarily disable problematic linters for Go 1.23 compatibility
    - staticcheck
    - gosimple
    - unused
    - nakedret

dupl:
  threshold: 50
gocyclo:
  min-complexity: 15
