repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/golangci/golangci-lint
    rev: v1.59.0  # Updated to a newer version
    hooks:
      - id: golangci-lint
        args: [--config=.golangci.yml, --fix]
        # Removed the --fix flag as it can cause issues with certain linters
        pass_filenames: false  # Run on all files, not just changed ones
        stages: [pre-commit]

  - repo: local
    hooks:
      - id: go-fmt
        name: go fmt
        entry: go fmt
        args: [./...]
        language: system
        types: [go]
        pass_filenames: false

      - id: go-imports
        name: goimports
        entry: goimports
        args: [-w, ./]
        language: system
        types: [go]
        pass_filenames: false

      - id: go-mod-tidy
        name: go mod tidy
        entry: go mod tidy
        language: system
        pass_filenames: false
